### ISSUE TITLE
PyCaffe has no attribute 'SolverParameter'

### ISSUE THREAD

**Issue by stevendbrown** [naibaf7/PyGreentea#5]
the `train.py` scripts in the examples both evoke the following error:

```
Traceback (most recent call last):
  File "./train.py", line 56, in <module>
    solver_config = pygt.caffe.SolverParameter()
AttributeError: 'module' object has no attribute 'SolverParameter'
```

PyCaffe seems to be importing correctly because at that same point in the code, pygt.caffe has other PyCaffe objects (e.g. SGDSolver, get_solver, etc.).

i'm currently running Caffe 1.0.0-rc3. is there an different version of Caffe i should try running?

**Comment by naibaf7** [comment]
@stevendbrown 
Yes it needs to run with a version of Caffe that exposes more internal C++ functions to Python.
These two will work:
https://github.com/naibaf7/caffe
https://github.com/BVLC/caffe/tree/opencl
Ignore the OpenCL part if you don't need it, you can compile it with CUDA and cuDNN only if you want, however LibDNN should be enabled in any case.

**Comment by stevendbrown** [comment]
thanks; PyGreentea runs very well on the BVLC/caffe/opencl branch.
